// legacy-vue/src/views/pages/Unauthorized.vue
<template>
    <div class="flex items-center justify-center min-h-screen bg-surface-50 dark:bg-surface-950">
        <div class="text-center">
            <div class="mb-8">
                <i class="pi pi-ban text-8xl text-red-500 mb-4"></i>
                <h1 class="text-4xl font-bold text-surface-900 dark:text-surface-0 mb-2">Access Denied</h1>
                <p class="text-lg text-surface-600 dark:text-surface-400 mb-8">
                    You don't have permission to access this resource.
                </p>
            </div>
            
            <div class="space-y-4">
                <Button 
                    label="Go Back" 
                    @click="goBack" 
                    icon="pi pi-arrow-left"
                    class="mr-2"
                />
                <Button 
                    label="Go to Dashboard" 
                    @click="goToDashboard" 
                    icon="pi pi-home"
                    severity="secondary"
                />
            </div>
            
            <div class="mt-8 text-sm text-surface-500 dark:text-surface-400">
                <p>If you believe this is an error, please contact your administrator.</p>
            </div>
        </div>
    </div>
</template>

<script setup>
import { useRouter } from 'vue-router';

const router = useRouter();

const goBack = () => {
    if (window.history.length > 1) {
        router.go(-1);
    } else {
        router.push('/');
    }
};

const goToDashboard = () => {
    router.push('/');
};
</script>

// src/app/[orgSlug]/unauthorized/page.tsx
"use client";

import { ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";

export default function UnauthorizedPage() {
  const params = useParams();
  const orgSlug = (params?.orgSlug as string) || "codevertex";
  return (
    <div className="flex min-h-[60vh] flex-col items-center justify-center gap-4 p-6 text-center">
      <div className="flex size-14 items-center justify-center rounded-full bg-destructive/10 text-destructive">
        <ShieldAlert className="size-7" />
      </div>
      <h1 className="text-xl font-bold text-foreground">Access denied</h1>
      <p className="max-w-md text-sm text-muted-foreground">
        You do not have permission to view this page. Contact your administrator if
        you believe this is a mistake.
      </p>
      <Link
        href={`/${orgSlug}`}
        className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground"
      >
        Back to dashboard
      </Link>
    </div>
  );
}
